/** @deprecated Import from `@/core/compactElementBranchVisibility`. */
export {
  activeMapHashEmbedSlotIds,
  activeMapHashPointerSlotIds,
  activeList2EmbedSlotIds,
  activeList2PointerSlotIds,
  activeListEmbedSlotIds,
  activeListPointerSlotIds,
  collectDescendantNodeIds,
  computeCompactHiddenNodeIds,
  computeListModeCollapsedBodyNodeIds,
  computeMapHashEmbedHiddenNodeIds,
  computeMapHashEmbedListCollapsedNodeIds,
  createCompactElementCanvasVisibility,
  createMapHashEmbedCanvasVisibility,
  inactiveMapHashEmbedSlotIds,
  inactiveMapHashPointerSlotIds,
  inactiveList2EmbedSlotIds,
  inactiveList2PointerSlotIds,
  inactiveListEmbedSlotIds,
  inactiveListPointerSlotIds,
  isNodeHiddenByMapHashEmbedPolicy,
  shouldCollapseBodyForMapHashEmbedList,
  type CompactElementCanvasVisibility,
  type MapHashEmbedCanvasVisibility,
} from '@/core/compactElementBranchVisibility'
